### PR TITLE
#25 - Geocoder service 

### PR DESCRIPTION
**Pull request by podarok**
Implementing #25 

See Change Record for this issue
https://www.drupal.org/node/2648356

Changelog
https://www.drupal.org/node/2648356

Can be merged. Not tested!!!
# ToDo
### From contrib/location/location.inc

for https://github.com/drupal-ukraine/dmaps/pull/40
- port location_map_link()
- port location_get_postalcode_data()
- port location_distance_between()
- port location_driving_directions_link()
- port _location_convert_distance_to_meters()
- port location_latlon_rough()
- port location_latlon_rough_default()
- port location_country_bounds()
- port location_latlon_exact()
- port _location_supported_countries()
- port location_get_provinces()
- port location_country_name()
- port location_province_name()
- port location_province_code()

### CODE REVIEW

**Comment by ddrozdik** [comment]
Related ticket applied here https://github.com/drupal-ukraine/dmaps/issues/37

**Comment by DmitryDrozdik** [comment]
I suggest move old function location_country_name() into LocationCountriesManager

**Comment by ddrozdik** [comment]
1. I have update list of services in the Roadmap file here https://github.com/drupal-ukraine/dmaps/pull/46, looks like we need more services for different parts.
2. Please check PR https://github.com/drupal-ukraine/dmaps/pull/46 and remove already ported functions from your PR.
3. Also I propose to use files directory in the module for all additional files, like supported counties. Please move then to /files/supported_countries/{file.name}

**Comment by ddrozdik** [comment]
@afi13 will finish this PR

**Comment by ddrozdik** [comment]
finished in the https://github.com/drupal-ukraine/dmaps/pull/52

**Pull request closed without merging**
